---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r code}
#Download the data
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", destfile = "activity.zip", mode="wb")
#Unzip the data 
unzip("activity.zip")
activity <- read.csv("activity.csv", header = TRUE)
act.complete <- na.omit(activity)
```


## What is mean total number of steps taken per day?
```{r code}
library(magrittr)
library(dplyr)
#Collapse the data and calculate the sum
act.day <- group_by(act.complete, date)
act.day <- summarize(act.day, steps=sum(steps))
summary(act.day)
#Create the histogram 
qplot(steps, data=act.day)
#Calculate the mean and the median 
mean(act.day$steps)
median(act.day$steps)
```


## What is the average daily activity pattern?
```{r code}
#Create the data frame and plot 
act.int <- group_by(act.complete, interval)
act.int <- summarize(act.int, steps=mean(steps))
ggplot(act.int, aes(interval, steps)) + geom_line()
#Find the interval with maximum steps 
act.int[act.int$steps==max(act.int$steps),]
```


## Imputing missing values
```{r code}
#Calculate the total number of missing values 
nrow(activity)-nrow(act.complete)
#Replace missing values with mean 
names(act.int)[2] <- "mean.steps"
act.impute <- merge(activity, act.int)
#Create a new filled dataset
act.impute$steps[is.na(act.impute$steps)] <- act.impute$mean.steps[is.na(act.impute$steps)]
#Generate the histogram
act.day.imp <- group_by(act.impute, date)
act.day.imp <- summarize(act.day.imp, steps=sum(steps))
qplot(steps, data=act.day.imp)
#Calculate mean and median
mean(act.day.imp$steps)
median(act.day.imp$steps)
```
The mean appears to be unaffected by this simple data imputation. The median is smaller.

## Are there differences in activity patterns between weekdays and weekends?
```{r code}
#Create new factor with 2 levels 
act.impute$dayofweek <- weekdays(as.Date(act.impute$date))
act.impute$weekend <-as.factor(act.impute$dayofweek=="Saturday"|act.impute$dayofweek=="Sunday")
levels(act.impute$weekend) <- c("Weekday", "Weekend")
#Make the pannel plot
act.weekday <- act.impute[act.impute$weekend=="Weekday",]
act.weekend <- act.impute[act.impute$weekend=="Weekend",]
act.int.weekday <- group_by(act.weekday, interval)
act.int.weekday <- summarize(act.int.weekday, steps=mean(steps))
act.int.weekday$weekend <- "Weekday"
act.int.weekend <- group_by(act.weekend, interval)
act.int.weekend <- summarize(act.int.weekend, steps=mean(steps))
act.int.weekend$weekend <- "Weekend"
act.int <- rbind(act.int.weekday, act.int.weekend)
act.int$weekend <- as.factor(act.int$weekend)
ggplot(act.int, aes(interval, steps)) + geom_line() + facet_grid(weekend ~ .)
```